name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - DEV
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - DEV

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Afficher la structure des fichiers avant le build
      - name: List initial project files
        run: ls -R

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build

      # Vérification de la présence du fichier index.html après le build
      - name: List build output files
        run: ls -R dist/orion-front

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_WAVE_088395403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Utilisé pour les commentaires sur les PRs
          action: "upload"
          app_location: "/"  # Dossier source du projet
          api_location: ""  # Pas d'API pour ce projet
          output_location: "dist/orion-front"  # Dossier contenant index.html après build

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_WAVE_088395403 }}
          action: "close"
