name: Build and deploy Node.js app to Azure Web App - asor44

on:
  push:
    branches:
      - PROD
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 18.10.0

      - name: Install dependencies
        run: npm install
        working-directory: Orion_front   # Assurez-vous que le chemin est correct

      - name: Build app
        run: npm run build --if-present
        working-directory: Orion_front   # Assurez-vous que le chemin est correct

      - name: Create artifact directory
        run: mkdir -p artifact-directory

      - name: Copy files to artifact directory
        run: cp -r Orion_front/dist/* artifact-directory

      - name: List artifact directory
        run: ls -R ${{ github.workspace }}/artifact-directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: artifact-directory   # Utilisez le répertoire temporaire créé

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'asor'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C3F2112F7F254D88B5976DFD879BF3D5 }}
          package: ${{ github.workspace }}   # Utilisez le répertoire temporaire

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: path/to/artifacts   # Assurez-vous que le chemin est correct
