name: Build and deploy Node.js app to Azure Web App - asor

on:
  push:
    branches:
      - PROD
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 18.10.0

      - name: Install dependencies
        run: npm install
        working-directory: Orion_front

      - name: Build app
        run: npm run build --if-present
        working-directory: Orion_front

      # You can uncomment the following line to run tests if needed.
      # - name: Run tests
      #   run: npm test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: Orion_front

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'asor'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C3F2112F7F254D88B5976DFD879BF3D5 }}
          package: ${{ github.workspace }}/Orion_front

